import Head from "next/head";
import Header from "../components/header";
import RelatedCard from "../components/related-card";
import StoryCard from "../components/story-card";
import TrendingCard from "../components/trending-card";
import { client } from "../prismic-configuration";
import Prismic from "prismic-javascript";
import TrendingSection from "../components/trending-section";
import StorySection from "../components/story-section";
import RelatedSection from "../components/related-section.js";

export default function Home({ stories, trendingArticles, alsoRead }) {
 
  return (
    <div>
      <Head>
        <title>Tippler Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="m-5 md:m-20">
        <TrendingSection data={trendingArticles} />
        <div className="mt-11 sm:grid md:grid justify-items-center lg:grid-cols-3 gap-11 3xl:flex">
          <StorySection data={stories} />
          <RelatedSection data={alsoRead} />
        </div>
      </section>
    </div>
  );
}

export async function getServerSideProps({ req }) {
  const stories = await client.query(
    Prismic.Predicates.at("document.type", "story")
  );

  const trendingArticles = await client.query(
    Prismic.Predicates.at("document.tags", ["trending"])
  );

  const alsoRead = await client.query(
    Prismic.Predicates.at("document.tags", ["also_read"])
  );

  return {
    props: {
      stories,
      trendingArticles,
      alsoRead,
    },
  };
}
